blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('xojiakbar.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xojiakbar/urls.py
from django.urls import path

from xojiakbar.views import HomePageView, UserLoginView, UserRegisterView, UserLogoutView, AboutView, HomeView, \
    PostFormView, UserPostsView, PostDetailView, PostConfirmDeleteView, UserPostsCreateView

app_name = 'xojiakbar'
urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('about/', AboutView.as_view(), name='about'),
    path('home/', HomeView.as_view(), name='home'),
    path('postform/', PostFormView.as_view(), name='post-form'),
    path('userposts/', UserPostsView.as_view(), name='user-posts'),
    path('postdetail/', PostDetailView.as_view(), name='post-detail'),
    path('postconfirmdelete/', PostConfirmDeleteView.as_view(), name='post-confirm-delete'),
    path('post/create', UserPostsCreateView.as_view(), name='post-create'),
]

xojiakbar/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Profile(AbstractBaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_img = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    location = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def str(self):
        return self.user.username


class Post(AbstractBaseModel):
    title = models.CharField(max_length=128)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def str(self):
        return self.user

xojiakbar/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from xojiakbar.models import Post


class UserRegisterModelFrom(forms.ModelForm):
    password1 = forms.CharField(max_length=100)
    password2 = forms.CharField(max_length=100)
    def save(self, commit=True):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 == password2:
            user = super().save(commit)
            user.set_password(password1)
            user.save()
        else:
            raise ValidationError("Password must match")

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]



class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)

class PostCreateForm(forms.ModelForm):
    model = Post
    fields = ["name", "content", "user"]

xojiakbar/views.py
from msilib.schema import ListView

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from xojiakbar.forms import UserRegisterModelFrom, UserLoginForm, PostCreateForm
from xojiakbar.models import Post


class HomePageView(View):
    def get(self, request):
        return render(request, 'xojiakbar/home.html')



class UserRegisterView(View):
    def get(self, request):
        form = UserRegisterModelFrom()
        return render(request, "xojiakbar/register.html", {"form": form})

    def post(self, request):
        form = UserRegisterModelFrom(data=request.POST)
        if form.is_valid():
            messages.success(request, "User registered successfully")
            form.save()
            return redirect('xojiakbar:login')
        else:
            return render(request, "xojiakbar/register.html", {"form":form})


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, "xojiakbar/login.html", {"form": form})

    def post(self, request):
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                print(request.COOKIES)
                messages.success(request, "User logged in successfully")
                return redirect("xojiakbar:home-page")
            else:
                messages.error(request, "Username or password is wrong")
                return redirect("xojiakbar:login")
        else:
            return render(request, "xojiakbar/login.html", {"form": form})


class UserLogoutView(View):
    def get(self, request):
        return render(request, "xojiakbar/logout.html")

    def post(self, request):
        logout(request)
        messages.info(request, "User logged out successfully")
        return redirect("xojiakbar:home-page")


class AboutView(View):
    def get(self, request):
        return render(request, "xojiakbar/about.html")


class HomeView(View):
    def get(self, request):
        return render(request, "xojiakbar/home.html")


class PostFormView(View):
    def get(self, request):
        return render(request, "xojiakbar/post_form.html")


class UserPostsView(View):
    def get(self, request):
        return render(request, "xojiakbar/user_posts.html")


class PostDetailView(View):
    def get(self, request):
        return render(request, "xojiakbar/post_detail.html")


class PostConfirmDeleteView(View):
    def get(self, request):
        return render(request, "xojiakbar/post_confirm_delete.html")


# class UserPostView(View):
#     def get(self, request):
#         return render(request, "xojiakbar/user_posts.html")


class UserPostsCreateView(CreateView):
    model = Post
    form = PostCreateForm
    fields = ['title', 'content', 'user']
    template_name = "xojiakbar/post_create.html"
    get_absolute_url = reverse_lazy('xojiakbar:post-form')

templates/xojiakbar/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'xojiakbar:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'xojiakbar:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'xojiakbar:about' %}">About</a>
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:post-form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:user-posts' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                <h1>About Page</h1>
                    <div class="container mt-5">
                        <h2>About Us</h2>
                        <p>Welcome to our Django Blog! This blog is dedicated to sharing knowledge, experiences, and thoughts on various topics.</p>

                        <h3>Our Mission</h3>
                        <p>Our mission is to provide valuable and insightful content to our readers. We aim to engage, educate, and entertain through our blog posts.</p>

                        <h3>Meet the Team</h3>
                        <p>We are a passionate team of writers, developers, and enthusiasts who love sharing our expertise with the world.</p>

                        <!-- Add more content about your team, mission, etc. -->

                        <p>Feel free to explore our blog and discover a wide range of articles covering different subjects.</p>
                    </div>

                </div>
                <div class="col-md-4">
                  <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                      </ul>
                    </p>
                  </div>
                </div>
              </div>
            </main>
        
            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        </body>
        </html>
        

templates/xojiakbar/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'xojiakbar:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'xojiakbar:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'xojiakbar:about'%}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:post-form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:user-posts' %}">Profile</a>


                    <a class="nav-item nav-link" href="{% url 'xojiakbar:logout' %}">Logout</a>

                {% else %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h3>Django messages might be shown here</h3>
              </div>
              <article class="media content-section">
                <img class="rounded-circle article-img" src="{% static 'corey.jpeg' %}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="{% url 'xojiakbar:user-posts' %}">Jordan Gibbs</a>
                    <small class="text-muted">Feb 19, 2023</small>
                  </div>
                  <h5><a class="article-title" href="{% url 'xojiakbar:post-detail' %}">I have been watching a decade.</a></h2>
                </div>
              </article>
              <article class="media content-section">
                <img class="rounded-circle article-img" src="{% static 'gibbs.jpeg' %}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="{% url 'xojiakbar:user-posts' %}">Jordan Gibbs </a>
                    <small class="text-muted">Feb 19, 2023</small>
                  </div>
                  <h2><a class="article-title" href="{% url 'xojiakbar:post-detail' %}">Do Gimmicky ChatGPT Prompts Actually Work?</a></h2>
                </div>
              </article>
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/xojiakbar/login.html
{% block title %} Login Page {% endblock %}
{% block body %}
    <h1>User Login Form</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}


    <button type="submit">Submit</button>

    </form>

{% endblock %}

templates/xojiakbar/logout.html
{% block title %} Log Out {% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        Are you sure to Log Out ? <br><br>
            <a><button type="submit">Yes</button></a>

        </form>
        <a href="{% url 'xojiakbar:home-page' %}">
                    <button>No</button></a>
{% endblock %}

templates/xojiakbar/post_create.html
{% block title %} Post Create {% endblock %}
{% block body %}
    <h1>Post Create Page</h1>
    <form method="post" action="{% url 'xojiakbar:post-create'%}">
        {{ form.as_div }}<br>
        {% csrf_token %}
        <button type="submit">Create Post</button>
    </form>

{% endblock %}

templates/xojiakbar/post_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'xojiakbar:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'xojiakbar:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'xojiakbar:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:post-form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:user-posts' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h3>Django messages might be shown here</h3>
              </div>
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{% static 'corey.jpeg' %}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'xojiakbar:user-posts' %}">RapidFork Technology</a>
        <small class="text-muted">Feb 19, 2023</small>
         <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="#">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'xojiakbar:post-confirm-delete' %}">Delete</a>
          </div>
        
      </div>
      <h2 class="article-title">I have been watching a decade.</h2>
      <p class="article-content">I have been watching a decade worth of The Ask Project
        by Corey Gil-Shuster on YouTube. Makes me have very little hope of there ever 
        being a two state solution. The Palestinians seem
        Makes me have very little hope of there ever 
        being a two state solution. The Palestinians seem
      </p>
    </div>
  </article>
</div>
<div class="col-md-4">
  <div class="content-section">
    <h3>Our Sidebar</h3>
    <p class='text-muted'>You can put any information here you'd like.
      <ul class="list-group">
        <li class="list-group-item list-group-item-light">Latest Posts</li>
        <li class="list-group-item list-group-item-light">Announcements</li>
        <li class="list-group-item list-group-item-light">Calendars</li>
        <li class="list-group-item list-group-item-light">etc</li>
      </ul>
    </p>
  </div>
</div>
</div>
</main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/xojiakbar/register.html
{% block title %} Register Page {% endblock %}
{% block body %}
    <h1> Registration Page</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Register</button>

    </form>

{% endblock %}

templates/xojiakbar/user_posts.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'xojiakbar:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'xojiakbar:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'xojiakbar:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:post-form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:user-posts' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'xojiakbar:register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h3>Django messages might be shown here</h3>
              </div>
            <h1 class="mb-3">Posts by Andrew Ng </h1>
         
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{% static 'andrew.jpeg' %}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'xojiakbar:user-posts' %}">Andrew Ng</a>
                  <small class="text-muted">Aug 21, 2019</small>
                </div>
                <h2><a class="article-title" href="{% url 'xojiakbar:post-detail' %}">AI in Latin America: Announcing our first international office in Colombia</a></h2>
                <p class="article-content">I am excited to announce the opening of our office in Medellín, Colombia. 
                  The office will serve as the Latin American headquarters for three of the companies in our AI ecosystem</p>
              </div>
            </article>
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{% static 'andrew.jpeg' %}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'xojiakbar:user-posts' %}">Andrew Ng</a>
                  <small class="text-muted">Aug 21, 2019</small>
                </div>
                <h2><a class="article-title" href="{% url 'xojiakbar:post-detail' %}">Introducing the AI Transformation Playbook</a></h2>
                <p class="article-content">Dear friends,
                  I’m excited to share with you the AI Transformation Playbook. Drawn from my experience leading Google Brain, 
                  Baidu’s AI Group, and Landing AI, this Playbook provides a roadmap for your company to transform into a great AI company.</p>
              </div>
            </article>
            
        
          </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>
      </div>
      </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
              